  name-template: 'Release $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver: package-json
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'maintenance'
template: |
  ## What's Changed

  $CHANGES

  ## Installation

  ```bash
  npm install ascii-side-of-the-moon
  ```

  ## Usage

  ```typescript
  import { getMoonState, renderMoon } from 'ascii-side-of-the-moon';
  
  const moonState = getMoonState(new Date());
  const asciiArt = renderMoon(moonState);
  console.log(asciiArt);
  ```

  ## Version: $RESOLVED_VERSION
