name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes (optional)'
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.package-version.outputs.version }} \
            --title "Release v${{ steps.package-version.outputs.version }}" \
            --notes "## What's Changed

          ${{ github.event.inputs.release_notes || 'Bug fixes and improvements' }}

          ## Version: ${{ steps.package-version.outputs.version }}

          ## Installation

          \`\`\`bash
          npm install ascii-side-of-the-moon
          \`\`\`

          ## Usage

          \`\`\`typescript
          import { getMoonState, renderMoon } from 'ascii-side-of-the-moon';

          const moonState = getMoonState(new Date());
          const asciiArt = renderMoon(moonState);
          console.log(asciiArt);
          \`\`\`" \
            --draft=false \
            --prerelease=false
