name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string
      release_notes:
        description: 'Release notes (optional)'
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: |
            ## What's Changed
            
            ${{ github.event.inputs.release_notes || 'Bug fixes and improvements' }}
            
            ## Installation
            
            ```bash
            npm install ascii-side-of-the-moon
            ```
            
            ## Usage
            
            ```typescript
            import { getMoonState, renderMoon } from 'ascii-side-of-the-moon';
            
            const moonState = getMoonState(new Date());
            const asciiArt = renderMoon(moonState);
            console.log(asciiArt);
            ```
          draft: false
          prerelease: false
